name: "Netflix Rows"
guid: "59a57aef-4760-41eb-a37d-bc112d5b163f"
version: "1.0.4.0"
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "YourUsername"
overview: "Netflix-style home screen rows for Jellyfin"
description: "Transforms your Jellyfin home screen into Netflix-style horizontal rows with configurable content sections"
category: "General"
artifacts:
- "Jellyfin.Plugin.NetflixRows.dll"
changelog: |
  ## v1.0.4
  - Fixed Jellyfin 10.10.7 compatibility with simplified API calls