name: "Netflix Rows"
guid: "6c0b8d8a-6b1c-4c5a-9b0a-1b2c3d4e5f6a"
version: "2.0.3.0"
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "FigmaCode"
overview: "Netflix-style home screen rows for Jellyfin"
description: "Transforms your Jellyfin home screen into Netflix-style horizontal rows with configurable content sections"
category: "General"
artifacts:
- "Jellyfin.Plugin.NetflixRows.dll"
changelog: |
  ## v2.0.3.0
  - Complete Netflix-style frontend integration with File Transformation support