name: Build and Release Plugin

on:
  push:
    tags: [ 'v*' ]  # Nur bei Tags ausführen
  pull_request:
    branches: [ main ]

permissions:          # <- Das hier hinzufügen
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore Jellyfin.Plugin.NetflixRows/Jellyfin.Plugin.NetflixRows.csproj
      
    - name: Build
      run: dotnet build Jellyfin.Plugin.NetflixRows/Jellyfin.Plugin.NetflixRows.csproj --no-restore -c Release
      
    - name: Upload Build Artifacts (PR only)
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: plugin-build
        path: publish/
        
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Build and Publish
      run: |
        dotnet restore Jellyfin.Plugin.NetflixRows/Jellyfin.Plugin.NetflixRows.csproj
        dotnet publish Jellyfin.Plugin.NetflixRows/Jellyfin.Plugin.NetflixRows.csproj -c Release -o publish/
        
    - name: Create Release Package
      run: |
        mkdir -p release
        cp publish/Jellyfin.Plugin.NetflixRows.dll release/
        cp meta.json release/
        cd release
        zip -r ../jellyfin-plugin-netflix-rows-${GITHUB_REF#refs/tags/}.zip .
        
    - name: Generate MD5
      id: md5
      run: |
        MD5=$(md5sum jellyfin-plugin-netflix-rows-${GITHUB_REF#refs/tags/}.zip | cut -d ' ' -f1)
        echo "md5=$MD5" >> $GITHUB_OUTPUT
        echo "Generated MD5: $MD5"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: jellyfin-plugin-netflix-rows-${{ github.ref_name }}.zip
        generate_release_notes: true
        body: |
          ## Netflix Rows Plugin ${{ github.ref_name }}
          
          **MD5 Checksum:** ${{ steps.md5.outputs.md5 }}
          
          ### Changes
          - Fixed Jellyfin 10.10.7 compatibility
          - Updated API calls to use BaseItemKind enums
          - Improved error handling
          
          ### Installation
          1. Download the ZIP file below
          2. Extract to your Jellyfin plugins directory: `jellyfin/plugins/NetflixRows/`
          3. Restart Jellyfin server
          
          Or install via repository: `https://raw.githubusercontent.com/FigmaCode/jellyfin-plugin-netflix-rows/main/repository.json`
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}